import '../assets/css/plugins/fontawesome-6.css';
import '../assets/css/plugins/swiper.min.css';
import '../assets/css/vendor/bootstrap.min.css';
// import './assets/css/vendor/jquery-ui.css';
import '../assets/css/vendor/magnific-popup.css';
import '../assets/css/vendor/metismenu.css';
import '../assets/css/style.css';
import localFont from "next/font/local";
// import Header from './component/header/header';

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TechStudent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
       <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Techstudent</title>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header/> */}
        {children}
      </body>
    </html>
  );
}
